CREATE DATABASE hbnb_db;

USE hbnb_db;

"""
utisisation VARCHAR
"""


CREATE TABLE User (
	id VARCHAR(36) PRIMARY KEY,
	email VARCHAR(120) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	is_admin BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE Place (
	id VARCHAR(36) PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL,
	description VARCHAR(256) UNIQUE NOT NULL,
	address VARCHAR(128) NOT NULL,
	latitude VARCHAR(36,0) UNIQUE NOT NULL,
	longitude VARCHAR(36,0) UNIQUE NOT NULL,
	host_id VARCHAR(36) UNIQUE NOT NULL,
	city VARCHAR(36) UNIQUE NOT NULL,
	price_per_night VARCHAR(36) NOT NULL,
	number_of_rooms VARCHAR(36) UNIQUE NOT NULL,
	number_of_batrooms VARCHAR(36) UNIQUE NOT NULL,
	max_guest VARCHAR(36) NOT NULL,
	is_admin BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE Amenity (
	id VARCHAR(36) PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL,
	place_id VARCHAR(36) UNIQUE NOT NULL,
	amenity_id VARCHAR(36) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE Review (
	id VARCHAR(36) PRIMARY KEY,
	place_id VARCHAR(36) UNIQUE NOT NULL,
	user_id VARCHAR(36) UNIQUE NOT NULL,
	comment VARCHAR(256) NOT NULL,
	rating VARCHAR(36,0) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE Country (
	id VARCHAR(36) PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL,
	code VARCHAR(3)  NOT NULL,
	cities VARCHAR(36) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);




CREATE TABLE City (
	id VARCHAR(36) PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL,
	country_id VARCHAR(36) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



CREATE TABLE Base (
	id VARCHAR(36) PRIMARY KEY,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
